# Generated by Django 4.2 on 2024-05-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_comment_blog_commen_created_0e6ed4_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
